### ISSUE TITLE
The Hidden item can't unhide

### ISSUE THREAD

**Issue by Tback1** [AlexBieg/obsidian-better-command-palette#97]
obsidian 1.1.16
Windwos 10 ltsc

1.hide the item
![image](https://user-images.githubusercontent.com/8872546/235517780-1cb0c468-69b2-45e3-a0c3-d15648a7493d.png)
2.after hide
![image](https://user-images.githubusercontent.com/8872546/235517841-a58f9c6e-6e23-430a-bdb5-5ae940abea7c.png)
3.try to unhide but nothing
![image](https://user-images.githubusercontent.com/8872546/235517860-994c56a3-5b3c-4b39-ab7a-7152e142fa18.png)

**Comment by alexinea** [comment]
I've had this problem too.

obsidian: 1.5.3
better command palette: 0.17.1

**Comment by alexinea** [comment]
I found out that this was due to plug-in conflicts.

I used the following CSS snippet to fix the problem:

```css
.better-command-palette .suggestion-item.hidden{
    display: flex!important;
}
```
